name: ci

on:
  push:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        run: go test -v -cover ./...
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
      
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.REGISTRY_URL }}/rtijm/hello-world:latest
            ${{ secrets.REGISTRY_URL }}/rtijm/hello-world:${{ github.run_number }}
      
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Set Context
        uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONTEXT }}
        id: setcontext

      - name: Create secret for registry
        uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ secrets.REGISTRY_URL }}
          container-registry-username: ${{ secrets.REGISTRY_USER }}
          container-registry-password: ${{ secrets.REGISTRY_PASS }}
          secret-name: my-k8s-registry-secret
    
      - name: Deploy
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: rtijm
          manifests: |
              k8s/deployment.yml
              k8s/service.yml
              k8s/ingress.yml
          images: ${{ secrets.REGISTRY_URL }}/rtijm/hello-world:${{ github.run_number }}
          kubectl-version: 'latest'
          imagepullsecrets: |
            my-k8s-registry-secret